/*
 * JoshNative - Useful Java Native APIs Copyright (C) 2011 Josh Kennedy
 *
 * This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

// JNI Header file, it's a good idea not to mess with this.. D:

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JoshNative */

#ifndef _Included_JoshNative
#define _Included_JoshNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JoshNative
 * Method:    _ClearScreen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JoshNative__1ClearScreen
  (JNIEnv *, jclass);

/*
 * Class:     JoshNative
 * Method:    _SetJavaConsoleTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JoshNative__1SetJavaConsoleTitle
  (JNIEnv *, jclass, jstring title);

/*
 * Class:     JoshNative
 * Method:    _ShowMessageBox
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_JoshNative__1ShowMessageBox
  (JNIEnv *, jclass, jint hwnd, jstring text, jstring title, jint options);

/*
 * Class:     JoshNative
 * Method:    _GetConsoleWindow
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JoshNative__1GetConsoleWindow
  (JNIEnv *, jclass);

/*
 * Class:     JoshNative
 * Method:    _SetTextColors
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JoshNative__1SetTextColors
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     JoshNative
 * Method:    _SetCursorPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JoshNative__1SetCursorPosition
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
